applied/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListeningList, ListeningDetail, ListeningCreate, ListeningDelete, ListeningUpdate

app_name = 'word_app'

urlpatterns = [
    path('list/', ListeningList.as_view(), name='list_applied'),
    path('detail/<int:pk>', ListeningDetail.as_view(), name='detail'),
    path('create/', ListeningCreate.as_view(), name='create'),
    path('delete/<int:pk>', ListeningDelete.as_view(), name='delete'),
    path('update/<int:pk>', ListeningUpdate.as_view(), name='update'),

]

blog/urls.py
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.index),
    path('<slug:pk>/', views.article),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views

#all users will be redirected to a common page after createing new accounts
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', views.index),
#     path('login/', views.Login.as_view()),
#     path('logout/', LogoutView.as_view()),
#     path('blog/', include('blog.urls')),
#     path('signup/', views.signup),
# ]


#users will be redirected to their individual pages after creating new accounts
app_name = 'mysite'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('blog/', include('blog.urls')),
    path('listening/', include('listening.urls')),
    path('applied/', include('applied.urls')),
    path('phrase/', include('phrase.urls')),
    path('signup/', views.signup),
    path('login_redirect/', views.login_redirect),
    path('home/', views.home, name='home'), #users' individual pages
]

listening/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListeningList, ListeningDetail, ListeningCreate, ListeningDelete, ListeningUpdate

app_name = 'listening_app'

urlpatterns = [
    path('list/', ListeningList.as_view(), name='list_gakuchika'),
    path('detail/<int:pk>', ListeningDetail.as_view(), name='detail'),
    path('create/', ListeningCreate.as_view(), name='create'),
    path('delete/<int:pk>', ListeningDelete.as_view(), name='delete'),
    path('update/<int:pk>', ListeningUpdate.as_view(), name='update'),

]

phrase/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListeningList, ListeningDetail, ListeningCreate, ListeningDelete, ListeningUpdate

app_name = 'phrase_app'

urlpatterns = [
    path('list/', ListeningList.as_view(), name='list_phrase'),
    path('detail/<int:pk>', ListeningDetail.as_view(), name='detail'),
    path('create/', ListeningCreate.as_view(), name='create'),
    path('delete/<int:pk>', ListeningDelete.as_view(), name='delete'),
    path('update/<int:pk>', ListeningUpdate.as_view(), name='update'),

]

templates/create.html
{% extends 'mysite/base.html' %}
{% block content %}
<form action="" method="POST">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="create">    
</form>
{% endblock content %}

templates/delete.html
{% extends 'mysite/base.html' %}
{% load my_tools %}
{% block content %}



<form action="" method="POST">
{% csrf_token %}
<input type="submit" value="delete"> 
</form>
{% endblock content %}

templates/detail.html
{% extends 'mysite/base.html' %}
{% load text_to_speech %}
{% load my_tools %}
{% block content %}
{% load static %}


{{ object.title|synthesize_speech }}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <div class="alert alert-success" role="alert">
      {{ object.title }}
      </div>
    {% with "listening/"|addstr:object.title|addstr:".mp3" as audio_name %}
    <figure>
      <figcaption>再生する</figcaption>
      <audio
          controls
          src="{% static audio_name|remove_space %}">
              Your browser does not support the
              <code>audio</code> element.
      </audio>
    </figure>
    {% endwith %}

    <div class="alert alert-primary" role="alert">
      <p>{{ object.memo | linebreaksbr }}</p>
      </div>
    

  </body>
</html>

{% endblock %}

templates/list_applied.html
{% extends 'mysite/base.html' %}
{% load func_test %}
{% load text_to_speech %}
{% load my_tools %}

{% block content %}
<div class="container">
    {% load static %}
    <h1>
        単語
    </h1>

    <a href="{% url 'word_app:create' %}" class="btn btn-info mb-2" tabindex="-1" role="button" aria-disabled="true">新規データ作成</a>

    {% for item in object_list reversed %}
    <div class="alert alert-primary" role="alert">

        <p>{{item.title}}</p>
        <p>{{ item.memo | linebreaksbr }}</p>


        <a href="{% url 'word_app:update' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">編集</a>
        <a href="{% url 'word_app:delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
        <a href="{% url 'word_app:detail' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">詳細</a>

    </div>
    {% endfor %}
</div>

{% endblock %}

templates/list_gakuchika.html
{% extends 'mysite/base.html' %}
{% load func_test %}
{% load text_to_speech %}
{% load my_tools %}

{% block content %}
<div class="container">
    {% load static %}
    <h1>
        リスニング
    </h1>

    <a href="{% url 'listening_app:create' %}" class="btn btn-info mb-2" tabindex="-1" role="button" aria-disabled="true">新規データ作成</a>

    {% for item in object_list reversed %}
    <div class="alert alert-primary" role="alert">

        <p>{{item.title}}</p>

        <a href="{% url 'listening_app:update' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">編集</a>
        <a href="{% url 'listening_app:delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
        <a href="{% url 'listening_app:detail' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">詳細</a>

    </div>
    {% endfor %}
</div>

{% endblock %}

templates/list_phrase.html
{% extends 'mysite/base.html' %}
{% load func_test %}
{% load text_to_speech %}
{% load my_tools %}

{% block content %}
<div class="container">
    {% load static %}
    <h1>
        フレーズ
    </h1>

    <a href="{% url 'phrase_app:create' %}" class="btn btn-info mb-2" tabindex="-1" role="button" aria-disabled="true">新規データ作成</a>

    {% for item in object_list reversed %}
    <div class="alert alert-primary" role="alert">

        <p>{{item.title}}</p>

        <a href="{% url 'phrase_app:update' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">編集</a>
        <a href="{% url 'phrase_app:delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
        <a href="{% url 'phrase_app:detail' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">詳細</a>

    </div>
    {% endfor %}
</div>

{% endblock %}

templates/update.html
{% extends 'mysite/base.html' %}
{% block content %}
<form action="" method="POST">
{% csrf_token %}
{{ form.title }}
{{ form.memo }}

<input type="submit" value="update">    
</form>
{% endblock content %}